services:
  db:
    image: postgres:17
    container_name: oknez_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: oknez
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: oknez_backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend  # Укажите путь к папке с Next.js
      dockerfile: Dockerfile
    container_name: oknez_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  postgres_data: